server:
  servlet.context-path: /api/assembleia
  port: 8080

spring:
  application.name: assembleia-api

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/assembleia

  rabbitmq:
    port: 5672
    username: admin
    password: admin

management:
  endpoint:
    liquibase:
      enabled: true
